settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  user_full_name: Alex Vesa # [First Name(s)] [Last Name]
  links:
    # Medium (only articles that are not under the paid wall work)
    - https://medium.com/decodingml/the-importance-of-data-pipelines-in-the-era-of-generative-ai-673e1505a861
    - https://medium.com/decodingml/the-3nd-out-of-11-lessons-of-the-llm-twin-free-course-ba82752dad5a
    - https://medium.com/decodingml/the-role-of-feature-stores-in-fine-tuning-llms-22bd60afd4b9
    # Substack
    - https://decodingml.substack.com/p/2-crucial-antipatterns-to-avoid-when?r=1ttoeh
    - https://decodingml.substack.com/p/the-role-of-feature-stores-in-fine?r=1ttoeh
    - https://decodingml.substack.com/p/change-data-capture-enabling-event?r=1ttoeh
    - https://decodingml.substack.com/p/the-importance-of-data-pipelines?r=1ttoeh
    - https://decodingml.substack.com/p/steal-my-code-to-solve-real-world?r=1ttoeh
    - https://decodingml.substack.com/p/framework-for-measuring-generative?r=1ttoeh
    - https://decodingml.substack.com/p/youre-not-digging-deeper-into-concepts?r=1ttoeh
    - https://decodingml.substack.com/p/do-not-evaluate-llm-summary-task?r=1ttoeh
    - https://decodingml.substack.com/p/dml-introduction-to-deploying-private?r=1ttoeh